"""empty message

Revision ID: 13488e98dbb8
Revises: d68a393e5768
Create Date: 2018-03-04 00:20:16.003092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13488e98dbb8'
down_revision = 'd68a393e5768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
